@extends('layouts.admin')
<!-- Generated by Laravel with the UI package -->
@section('content')
    <section class="section">
        <h1 class="title">{{ __('Dashboard') }}</h1>
        @if (session('status'))
            <article class="message is-primary">
                <div class="message-header">
                    <p>Success!</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
                <div class="message-body">
                    {{ session('status') }}
                </div>
            </article>
        @endif
        <h2 class="subtitle">
        {{ __('You are logged in!') }}
        </h2>
    </section>
@endsection
