@extends('layouts.admin')
<!-- Generated by Laravel with the UI package -->
@section('content')
    <section class="section">
        <h1 class="title">{{ __('Image ' ) . $image->original_name }}</h1>
        <hr>
        <img src="{{ 'https://laravel-resource.s3-ap-southeast-2.amazonaws.com/profiles/profile-' . $image->original_name }}" alt="{{$image->original_name}}" />
    </section>
@endsection