@extends('layouts.admin')
<!-- Generated by Laravel with the UI package -->
@section('content')
    <section class="section">
        <h1 class="title">{{ __('Image ' ) . $image->original_name }}</h1>
        <hr>

         @php $postFiles = App\Models\Post::find(67)->files; @endphp

        <img src="{{ asset('images/' . $image->original_name) }}" alt="{{$image->original_name}}"/>
    </section>

@endsection