@extends('layouts.admin')
<!-- Generated by Laravel with the UI package -->
@section('content')
    <section class="section">
        <h1 class="title">{{ __('Upload images') }}</h1>
        <hr>
        <form action="{{ route('admin.images.save') }}" method="post" enctype="multipart/form-data">
 
        @csrf 
        <div class="field">
            <label class="label">Upload Image</label>
            <div class="control">
                <input class="input" name="uploadFile" type="file" value="{{ old('image') ?? null}}">
            </div>
            @error('image')<p class="help is-danger">{{ $message }}</p>@enderror
        </div>

        <div class="field is-grouped">
            <div class="control">
                <button type="submit" class="button is-link">Submit</button>
            </div>
            <div class="control">
                <a href="{{ route('admin.dash') }}" class="button is-link is-light">Cancel</a>
            </div>
        </div>
    </section>
@endsection